import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import {
  ClerkProvider,
  
 
} from "@clerk/nextjs";

// Import and use font classes
const geistSans = Geist({ subsets: ["latin"] });
const geistMono = Geist_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className} antialiased`}>
    
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          
            {children}
          </ThemeProvider>
   
      </body>
    </html>
    </ClerkProvider>
  );
}
